SET IDENTITY_INSERT [dbo].[Student] ON
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (1, N'Melissa', N'Manikam', N'mel.manikam@gmail.com', N'0211098897')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (2, N'Sujal', N'Chad', N'sujalchad@gmail.com', N'0273253466')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (3, N'Winnie', N'Hok', N'winniehok@gmail.com', N'0278279273')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (4, N'Sophie', N'Howaick', N'sophiehowaick@yahoo.com', N'0220263712')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (5, N'Celine', N'Dion', N'celinedion@hotmail.com', N'0278782962')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (6, N'Jared', N'Chang', N'jaredchang@avcol.school.nz', N'0237382638')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (7, N'Tony', N'Smith', N'tonysmith@gmail.com', N'0226375372')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (8, N'William', N'Clinton', N'williamclinton@gmail.com', N'0229402372')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (9, N'Mike', N'Zholyu', N'mikezholyu@gmail.com', N'0218269826')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (10, N'Shaam', N'Prasad', N'shaamprasad@gmail.com', N'024827828')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (11, N'Apirathy', N'Suli', N'apisuli@gmail.com', N'0272262432')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (12, N'Kelly', N'Chour', N'kellychour@gmail.com', N'0272262249')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (13, N'Ammara', N'Bhickhoo', N'ammarabhickoo@gmail.com', N'0228726295')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (14, N'Nina', N'Huvel', N'ninahuvel@gmail.com', N'02462786378')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (15, N'Jacky', N'Zhong', N'jackyzhong@gmail.com', N'02469746378')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (16, N'Josh', N'Syed', N'joshsyed@gmail.com', N'02162786378')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (17, N'Manny', N'Munet', N'mannymunet@gmail.com', N'0246382978')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (18, N'Tommy', N'Thompson', N'tommythompson@gmail.com', N'02262379353')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (19, N'Jimmy', N'Jackson', N'jimmyjackson@gmail.com', N'02468286378')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (20, N'Kim', N'Khardashian', N'kimkhardashian@gmail.com', N'0215275281')
INSERT INTO [dbo].[Student] ([StudentID], [FirstName], [LastName], [Email], [PhoneNumber]) VALUES (21, N'Lucy', N'Lemon', N'lucylemon@gmail.com', N'02159265281')

SET IDENTITY_INSERT [dbo].[Student] OFF